### PR TITLE
Addresses #16.

### PR DESCRIPTION
**Pull request by AndrewSales**

### CODE REVIEW

**Comment by AndrewSales** [comment]
My bad; I think I have a pic of Jenny S too.

**Comment by sgmlguru** [comment]
Thanks for the fixes, Andrew. The photos page now looks weird on my screen. Narrow columns and words broken in two by line breaks. Not sure what happened there but it looks like the demojam pics are in two columns out of three - the other pics cover all three.

I don't trust myself with fixing and merging, but feel free to when you've addressed the above.

**Comment by AndrewSales** [comment]
Bootstrap 4 docs say that cards aren't responsive, so suspect that's the underlying problem. If I add more pics, they flow into rows of three; note that they don't either in the last group under "Questions from the floor". You can set `text-nowrap` on the image captions, but then they flow over the edge of the card border.
I'm very willing to improve this, but it will take some tinkering (carousels, anyone?). In order that we publish and have them to tweet about, I'd suggest either:

1. removing the sponsor/sister/social media side panels, so that the images have more room to breathe and so the effect you observe is lessened;
1. placing the images together on a site more attuned to the interactive display of same, e.g. Flickr, and linking there - I believe Balisage do/did this.

(P.S. coincidentally, fresh slide mounts have just arrived in the post: simpler times...?)

**Comment by sgmlguru** [comment]
I don't like removing the sponsors or the sister conferences from the page. The Flickr idea is a better one.

**Comment by AndrewSales** [comment]
Can you take another look, please? The viewports vary in size I assume because the images don't all have the same aspect ratio.

**Comment by sgmlguru** [comment]
I think what happens is that the carousel - or rather the CSS - sets the same width for every photo, actually. I'm not sure we can do a whole lot about it so I suggest we go with this one.

**Pull request merged**
